"""migration for item model

Revision ID: fc7185565d17
Revises: 04f34a70cc71
Create Date: 2025-12-04 11:38:35.780033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7185565d17'
down_revision: Union[str, Sequence[str], None] = '04f34a70cc71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=30), nullable=False),
    sa.Column('item_desc', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
